### ISSUE TITLE
Feature request: Disable red flashing on portraits while low hp

### ISSUE THREAD

**Issue by shocker13** [leatrix/leatrix-plus-wrath#116]
Greetings. It would be great to have an option to disable red flashing that occurs under 20% hp on target and focus portraits. 
![n4SJZB0](https://user-images.githubusercontent.com/18690368/184302582-806e344e-aacb-48fd-8a76-7c74e7b0f591.gif)
P.S. Thank you for your work.

**Comment by leatrix** [comment]
Suggestions appreciated.
