### ISSUE TITLE
Enhanced professions: Enchanting does not show item tooltips

### ISSUE THREAD

**Issue by 0blu** [leatrix/leatrix-plus-wrath#120]
When using the "_enhanced professions_" feature for _Enchanting_ the reagent items do not show tooltips for other addons; on other professions it does.

<img width="460" alt="image" src="https://user-images.githubusercontent.com/7039020/186989922-46be9be2-f995-4861-9dd0-66056e5bf466.png">

<img width="324" alt="image" src="https://user-images.githubusercontent.com/7039020/186989135-0afa6e0a-f468-48af-9328-643adb043537.png">

<img width="420" alt="image" src="https://user-images.githubusercontent.com/7039020/186989108-f3861c42-e209-434a-9725-7ebbef22da33.png">

Tested with ATT, BagBrother, TSM and a lot more.

Using Leatrix version `BCC 2.5.120` on game version `2.5.4 44833`.

**Comment by leatrix** [comment]
This seems to be the case without Enhance professions too (tested ATT and TSM).  It doesn't seem to be anything to do with LTP.

**Comment by 0blu** [comment]
Oh you are right, somehow I did not verify this case, but is it still fixable?

**Comment by leatrix** [comment]
Wrath pre-patch is out in a couple of days.  Wrath game code includes changes to the enchanting window so as long as the addons are updated for Wrath, that should solve the problem.

On the Wrath test realm, TSM does show the detailed tooltips for materials in the enchanting window.  In BCC, the detailed tooltips are not shown.  So wait until the addons are updated for Wrath and then the problem should be solved.

**Comment by 0blu** [comment]
Closing this for now. Maybe when BCC-SoM is released, and the blizzard base is not fixed this should be reopened.

**Comment by leatrix** [comment]
It's nothing to do with LTP.  It's an issue with other addons.  It's unlikely to be a feature added to LTP.  Wrath will probably fix the broken addons as long as those addons are updated for Wrath.  If Blizzard do make a BCC-SoM server and other addons don't work with it, you will need to contact the authors of those addons.
