### ISSUE TITLE
Feature Request: Manage repair frame

### ISSUE THREAD

**Issue by sMuve** [leatrix/leatrix-plus-wrath#122]
Hi there,
I love your addon and if I would be able to only keep one, it would be LTP!

However it seems that the repair frame is not managable via LTP and when managing the minimap plus resizing it, it looks like this for me
![image](https://user-images.githubusercontent.com/25771494/187071801-2572b960-6552-40c0-879b-98ed68cff9ee.png)

It would be awesome, if it could be managed an moved/scaled 

Thanks for your work! I highly appreciate it :)

**Comment by leatrix** [comment]
If you are not using the default UI right-side action bars, have you tried adjusting the cluster scale in the Enhance minimap configuration panel?  Adjusting the cluster sale affects the frames anchored to the minimap including the durability frame and objective tracker.

**Comment by sMuve** [comment]
So yeah, I have changed the cluster scale and now I can see the objectives/repair frame. However my right actions bars are now alos way more at the bottom of the screen.
I guess this is related to using "Dark Mode UI" which slightly modifies the basic UI.

**Comment by sMuve** [comment]
Ah sorry completly missed the info of the cluster scale. I want - for now - try to play with less addons. So I will maybe just re-arrange details in the bottom right corner.
Thank you for the support and considerung my suggestion.

**Comment by leatrix** [comment]
I will most likely add a durability frame mover in the next update.

**Comment by leatrix** [comment]
There's a new option 'Manage durability' ('Frames') in 3.0.01.alpha.2.
