### ISSUE TITLE
Recent update

### ISSUE THREAD

**Issue by plzfix** [leatrix/leatrix-plus-wrath#123]
The recent update is quite messy. 2/3rd of the features i was using on leatrix plus are now gone due to "cannot be used to elvui"
Namely : manage frames and manage buffs

Even when elvui doesn't have unitframes or buffs enabled, still can't use the features on leatrix plus.
Without a fix, rollback or change from your side i will just configure elvui and get rid of leatrix plus.

It's a shame because i enjoyed it quite a lot, thanks for reading me

**Comment by leatrix** [comment]
There are some changes in the latest alpha (for Wrath/pre-patch only):
https://github.com/leatrix/leatrix-plus-wrath/issues/121#issuecomment-1229413451

Manage buffs and Manage frames are included in the changes so you should be able to use both as long as you don't have ElvUI configured to disable the relevant Blizzard frames.

Alpha changes will be live for everyone on Wednesday as usual.

The point of the locks is not to restrict the addon for ElvUI users.  It is to avoid conflict reports being submitted to ElvUI support for options that are not compatible with ElvUI or specific ElvUI modules.  For example - 'Hide the combat log' works fine with Blizzard's chat feature.  But it does not work with ElvUI's chat module so now LTP will prevent that option from being used if ElvUI's chat module is enabled.

If you feel that further tweaks are needed to the locks (i.e. if you were using something before and had no issues with it but cannot use it now), let me know.
