### ISSUE TITLE
Wrong quest name displayed on quest turn-in

### ISSUE THREAD

**Issue by silverhawke249** [leatrix/leatrix-plus-wrath#124]
If the "Show quest level" option is enabled, the quest turn-in dialog will show the name of the last viewed quest in the quest log, instead of the quest's actual name.

Without "Show quest level":
![image](https://user-images.githubusercontent.com/50395934/187675240-264a3366-0923-4a17-8982-3ee635849073.png)

With "Show quest level":
![image](https://user-images.githubusercontent.com/50395934/187675309-0a8cfe9d-3380-4dcc-98c5-720eb6447d17.png)

**Comment by leatrix** [comment]
Thanks for the report.  Should be fixed in 3.0.01.

**Comment by tap3ah** [comment]
Just to note, the quest whose name is shown is the one selected in quest log. I thought it might be helpful.
