### ISSUE TITLE
[feature request] More control for "Enhance quest log" option

### ISSUE THREAD

**Issue by anzz1** [leatrix/leatrix-plus-wrath#127]
Simple thing really, please put the "Larger Quest Log" option behind the gear options in "Enhance quest log", like the "Show quest levels" already is. I don't really like the larger quest log which takes more screen space but it's currently impossible to use the "show quest levels" option without using the larger frame too.

**Comment by leatrix** [comment]
That's a good idea.  Added to 3.0.02.alpha.1.

**Comment by anzz1** [comment]
Further improvements in #129
