### ISSUE TITLE
Feature Request: Shaman Totem Bar Durations

### ISSUE THREAD

**Issue by Mayron** [leatrix/leatrix-plus-wrath#130]
I'd rather not find another addon for this and it seems minor. I could potentially make this feature myself but it feels like a good fit for this addon in the `Interface` tab and it seems overkill to build a separate addon for something as simple as a fixed visual label with a timer in it. 

I use Bartender and SUF and even these addons don't support this which seemed very odd (Bartender just lets you show the default bar and move its position).

I'd like to see durations, in the format of mm:ss such as "04:30" for 4 mins, 30 seconds remaining, above my totem action buttons on the totem bar for active totems.

I created this in photoshop to show what that might look like:

![totem-bar-durations](https://user-images.githubusercontent.com/5854995/188310460-69147599-e0ca-46d9-9003-ea8e2807cff4.png)

I'd ideally like to have a slightly transparent black background and white text over it like in the image above, but up to you. Maybe those could be settings.

**Comment by leatrix** [comment]
Feedback appreciated.  This isn't something I'm looking to add at the moment.
