### ISSUE TITLE
Feature Request: In Mute Game Sounds, please add an option to disable Beacon of Light healing sound. 

### ISSUE THREAD

**Issue by denumerable** [leatrix/leatrix-plus-wrath#131]
As a tank, I have never been more annoyed in my life. I literally had to turn off my game sound because it was non-stop.

I will happily join your Patreon or sub to your Twitch if you are able to fix this (if you have it). Leatrix has been one of the my favorite add ons for WoW for the last few years. Thank you for your work. <3

**Comment by leatrix** [comment]
This is too specialised for the Mute game sounds option so I will explain how to mute the spell sound another way.

There are a few sound file IDs for the Beacon of Light spell.  You can hear them all [here](https://www.wowhead.com/wotlk/spell=53563/beacon-of-light#sounds).

So there is a precast sound, a holy cast sound and an impact sound.

These are the sound file IDs for each component:

Precast: 568440
Holy cast: 569763
Impact: 569060, 567998 and 568764.

Enter the sound file IDs into an addon such as [MuteSoundFile](https://www.curseforge.com/wow/addons/mutesoundfile) to mute them.

**Comment by denumerable** [comment]
You are a hero. I will do that.

Thank you so much. Please let me know if you have a Patreon or Twitch channel so I can sub. :)
