### ISSUE TITLE
Feature Request: In-Battleground Timer

### ISSUE THREAD

**Issue by jonah-dev** [leatrix/leatrix-plus-wrath#133]
# Summary

Ideally I'd like to have a timer that reflects how long I have until the gate opens for the battleground. As it stands, I think that information is only available in the chatbox?

One would need to identify if timer lengths are consistent across all battlegrounds and then start the timer based on when the character actually enters the battleground.

From a UI perspective the existing "ready timer" could be grouped under a field called "Show Battleground Timers" with a cog to enable the in-bg timer. This option would be disabled by default to not change any existing functionality.

# Screenshots

![image](https://user-images.githubusercontent.com/55425221/188747079-c06d8f30-afb4-4bb1-a24f-24fac75db4e1.png)

# Notes

I'd be very willing to write this myself by the way but looking for a green light from the code owner. I haven't written any LUA but I'm sure I could figure it out.

**Comment by leatrix** [comment]
Feedback appreciated.
