### ISSUE TITLE
Feature Request: Add option to collapse quest log by default

### ISSUE THREAD

**Issue by jonah-dev** [leatrix/leatrix-plus-wrath#134]
This one is fairly minor and I'll keep it short. Visually the quest log can be a bit overwhelming when you have 10-15 different zones. I'd love to be able to collapse them all by default so I could just expand the zone I'm interested in. Alternatively you could expand only the option for the zone you're currently in, if it holds true that you have a quest in the zone you are currently in.

Feel free to close this one if you aren't a fan of the idea.

Again, I will write this if you are good with it.

**Comment by leatrix** [comment]
In 3.0.05.alpha.2 and higher, you can click the quest log count (top-left of the quest log frame) to expand or collapse all quest headers.  So you can click it to collapse all the headers then expand whichever header(s) you're interested in.

**Comment by jonah-dev** [comment]
Awesome. Thanks for the quick feedback and I appreciate the work you're doing.
