### ISSUE TITLE
Enchanced tooltip bug - Wrong order for level text on russian client

### ISSUE THREAD

**Issue by thehallowedfire** [leatrix/leatrix-plus-wrath#135]
Hello.
There is a bug with enchanced tooltips on russian client.

On russian client we have a little bit complicated system for level text in tooltips.
Without any enchancement it shows text like this:
![image](https://user-images.githubusercontent.com/112851853/188924308-53856f95-cde3-4ff3-b7c0-fae850f8eb74.png)
```Python
Ригглфазз    ## Name
Гуманоид 37-го уровня    ## literally says "Humanoid [of] 37-th level" and uses genitive (I think ;)) case for level text.
Пиратская Бухта    ## Faction
```

or for dead creatures:
![image](https://user-images.githubusercontent.com/112851853/188926690-5320f44f-9abe-4465-bc68-134058ec8cec.png)
```Python
Ригглфазз    ## Name
Труп существа 37-го уровня    ## "Body [of] creature [of] 37-th level". Still genitive case.
Пиратская Бухта    ## Faction
```

With enchanced tooltips enabled (LTP Wrath) it shows level text in a wrong order:
![image](https://user-images.githubusercontent.com/112851853/188928146-b21cfa2a-b9e3-42c1-9a92-baa90619991a.png)
```Python
Ригглфазз    ## Name
-й уровень 37 Гуманоид    ## "-th level 37 Humanoid". Now it uses nominative case for level text.
Пиратская Бухта    ## Faction
```

for dead creatures it uses the same text as without enchancement of tooltip - correct text.
![image](https://user-images.githubusercontent.com/112851853/188931398-22c913c0-c8c3-4af4-9669-1bf1b88554f3.png)

On TBC client with enchanced tooltips it looked like this:
```Python
Ригглфазз    ## Name
Уровень 37 Гуманоид    ## "Level 37 Humanoid". Word "Уровень" (Level) is in nominative case.
Пиратская Бухта    ## Faction
```
which was fine.

Could you please use this fix for Wrath LTP as well?

**Comment by leatrix** [comment]
Though it's never going to be perfect for your locale, please try 3.0.06.alpha.3.  It includes some updates to the tooltip information line.

The reason that dead creature tooltips look fine is because they are unmodified except for the grey unit name.  It's always been like that for all locales.

**Comment by thehallowedfire** [comment]
Now it looks like this:
![image](https://user-images.githubusercontent.com/112851853/188993167-ca6ca05a-597f-49d2-8f7a-b7841ea8aeaf.png)
```Python
Ригглфазз    ## Name
Гуманоид 37 уровня    ## "Humanoid [of] 37 level"
Пиратская Бухта    ## Faction
```
It looks correct. But if you could add the ending "-го" (meaning is "-th") after a number it will be ideal. It always stays "-го" with all level numbers.

By the way there is a little bit different format for creatures that don't have type in the tooltip. Like this one:
![image](https://user-images.githubusercontent.com/112851853/188994313-a05b6d76-368a-4863-93ad-7f3d537beb69.png)
```Python
Мартек Изгой    ## Name
42-й уровень    ## "42-th level" - nominative case
````
In this case it looks correct and unchanged.

**Comment by leatrix** [comment]
3.0.06.alpha.4 adds -ro to the level number of modified tooltips.  Friendly NPC tooltips are typically unmodified other than the unit name color (just as with dead unit tooltips).
