### ISSUE TITLE
Feature Request Add character item level

### ISSUE THREAD

**Issue by zdinch** [leatrix/leatrix-plus-wrath#139]
Hello! thanks for the addon, it's amazing!

Could the character's itemlevel be added to the character panel? in LK the itemlevel is used a lot and it would be incredible.

It could also be added to the tooltip and when you inspect someone their itemlevel but this will be more difficult.

Thank you and sorry for my english! :D

**Comment by Nillx** [comment]
Yeah i was thinking about this as well. Would be nice to be able to see ilvl on item's tooltips. Seeing my char's ilvl could be nice too.
![Screenshot-2022-09-25-040236](https://user-images.githubusercontent.com/34476875/192124008-31502e30-d1cc-430d-93ff-fde8cf865464.jpg)
![Untitled-1](https://user-images.githubusercontent.com/34476875/192124012-4aa0e849-2cad-440b-843d-e03e58698249.jpg)

Maybe something like this?

**Comment by zdinch** [comment]
> Maybe something like this?

Yes, something like that would be perfect.

**Comment by leatrix** [comment]
Suggestions appreciated.
