### ISSUE TITLE
Bug: No gossip automation with <Steam-Powered Auctioneer> in Dalaran

### ISSUE THREAD

**Issue by fearkite** [leatrix/leatrix-plus-wrath#145]
Hey Leatrix!

First of all, absolutely awesome addon. Love your work!

An easy one for ya;

Gossip automation doesn't function when enabled with the new Brassbolt Mechawrench <Steam-Powered Auctioneer> in Dalaran.

Thanks heaps! <3

**Comment by leatrix** [comment]
Please take a screenshot of the gossip window and attach it here.

**Comment by fearkite** [comment]
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/54443851/193179156-9f324242-905a-42d8-9cd1-ec51d61a3368.png">


There you go. :) 

Thanks again, Leatrix

**Comment by leatrix** [comment]
Many thanks for the screenshot.  Added to 3.0.16.alpha.1 for Brassbolt Mechawrench (Alliance) and Reginald Arcfire (Horde).

**Comment by capSAR273** [comment]
I have 3.0.22 LTP and still no automation for the NPC, should I try clearing the addon's saved variables?

**Comment by leatrix** [comment]
There's no need to delete saved variables.  Just ensure that 'Automate gossip' is enabled and you aren't holding the shift key when you talk to the NPC.  As I am not able to test it, maybe @fearkite can let me know if it works or not.

In the meantime, [update LTP to 3.0.22](https://www.curseforge.com/wow/addons/leatrix-plus-wrath/files) (release, not alpha), reload your UI, target the auctioneer NPC and enter **/ltp gossinfo**.  It will print some information in chat and attempt to select the first gossip option.  Screenshot the results, attach them here, and let me know if the command succeeds in opening the auction house frame, please.

**Comment by fearkite** [comment]
Working correctly for me with Bassbolt Mechawrench. Cannot test the Horde counterpart though.
Automates properly and holding shift key whilst interacting with said NPC disables automation.

**Comment by capSAR273** [comment]
> There's no need to delete saved variables. Just ensure that 'Automate gossip' is enabled and you aren't holding the shift key when you talk to the NPC. As I am not able to test it, maybe @fearkite can let me know if it works or not.
> 
> In the meantime, [update LTP to 3.0.23.alpha.1](https://www.curseforge.com/wow/addons/leatrix-plus-wrath/files/all), reload your UI, talk to the auctioneer NPC (so that the gossip frame opens) and enter **/ltp gossinfo**. It will print some information in chat and attempt to select the first gossip option. Screenshot the results, attach them here, and let me know if the command succeeds in opening the auction house frame, please.

Using **/ltp gossinfo** reports "Invalid Parameter" in the chat window, on 3.023.alpha.1 when speaking to the Horde auctioneer Reginald.

**Comment by leatrix** [comment]
You appear to be using an older version of LTP.  What version does it show in the configuration panel (top-left)?   Delete the addon folder completely and reinstall the latest alpha (currently 3.0.23.alpha.3).  Using [CurseForge App](https://download.curseforge.com/) is the best way to make sure the addon is always up-to-date.

Invalid parameter means the gossinfo command doesn't exist.  It was added in 3.0.22 and updated in 3.0.23.alpha.1.  [Here](https://github.com/leatrix/leatrix-plus-wrath/commit/c51d1485f52b2d5fda36230bebaec4d31446811d) is gossinfo in 3.0.22 and [here](https://github.com/leatrix/leatrix-plus-wrath/commit/b3c0f0031c7f17ed6fa38d5f85e722bc74acb6ab) it is updated in 3.0.23.alpha.1.

Both the Alliance and Horde NPC IDs (35607 and 35594) were added in 3.0.16. 
 [Here](https://github.com/leatrix/leatrix-plus-wrath/commit/fb3f21426408e11d2a81b56bae4a2ccdb3c1445d) is 3.0.16.alpha.1 showing both of the NPC IDs (35594 and 35607).

So if you are not seeing any of these things, you must be using an old version of the addon.

**Comment by capSAR273** [comment]
Hmm, I updated the addon using CF, but when I /ltp the top left shows 3.0.13. Not sure why all the "updates" CF has shown for LTP never actually updated the addon. I removed the addon folder and re-downloaded the latest alpha, but the top left still shows WC 3.0.13.
![image](https://user-images.githubusercontent.com/5252505/194086035-234a587b-5688-4d2f-a725-238ea5bf2b69.png)

**Comment by leatrix** [comment]
Do you have a screenshot of the addon in your addon listing in CurseForge App?  So under My Addons, scroll down until the row for Leatrix Plus is visible then take a screenshot of that row (don't click the addon name).
Like this:
![image](https://user-images.githubusercontent.com/58888415/194088003-ea6db7c4-a65f-45d9-9e79-596ff6abe6d4.png)

**Comment by leatrix** [comment]
Also, at the top-right of CurseForge App, there is a dropdown menu which allows you to choose your game.  Put your pointer over the menu and the tooltip will show the location of the addons on your computer, like this:

![image](https://user-images.githubusercontent.com/58888415/194089635-9e0303fa-e908-4c9c-b26d-2ea660bb2a7b.png)

Is that the correct location?  You said that you installed the latest release with CurseForge App but the addon version shown in game is old.  So maybe CurseForge App is updating to a different folder than the one where your actual Wrath game is.

**Comment by capSAR273** [comment]
OH my gosh I had it pointing to the Wrath Classic Beta....LOL thank you man, amazing addons and very helpful. Now to update all these addons I have forgotten for weeks...
