### ISSUE TITLE
Request: A little more flight times settings

### ISSUE THREAD

**Issue by BalurPoco** [leatrix/leatrix-plus-wrath#147]
Hi there!

I have two humble suggestions for the display of flight times:
- Inverted animation: I'd really love to reverse the flight bar animation, increase instead of decrease.
- Bar texture: My icons are skinned with Masque, and I use SharedMedia to change bar textures. Please add an option to change the bar textures.

**Comment by BalurPoco** [comment]
I beg your pardon. I tried to get the desired result in lua, it worked, but it would be better as a setting. :)

In Leatrix_Plus.lua:
Replaced line 5108 to `local texture = "Interface\\AddOns\\ShadowedUnitFrames\\media\\textures\\Charcoal"`
Added a new line before 5280 with `mybar:SetFill(true)`

**Comment by leatrix** [comment]
In 3.0.17.alpha.1, you can set the bar to fill up instead of drain using a new setting in the configuration panel.

**Comment by BalurPoco** [comment]
Thank you very much.
