### ISSUE TITLE
Request: Item Level in tooltip

### ISSUE THREAD

**Issue by skidstein** [leatrix/leatrix-plus-wrath#148]
It seems blizzard has not included the ability to show item level in item tooltips. I was wondering if the Leatrix team could add this to their enhanced tooltip functionality.

thanks,

**Comment by skidstein** [comment]
here is the original blizzard functionality

![Project-Epoch_k2j49z5DEV](https://user-images.githubusercontent.com/114864093/193483758-1091e65b-fd36-4cd2-ae19-236653b9e860.p
![Project-Epoch_Kn4NH8LVCA](https://user-images.githubusercontent.com/114864093/193483799-209aa761-35ea-4ce6-886f-b0064d87c878.png)
ng)

**Comment by leatrix** [comment]
Feedback appreciated.
