### ISSUE TITLE
Flight details

### ISSUE THREAD

**Issue by jbreckel** [leatrix/leatrix-plus-wrath#149]
Hope it's okay to post flight details here?

```
Flight details (WRATH): Fizzcrank Airstrip (0.21:0.49) to Dalaran (0.52:0.38) (Alliance) took 315 seconds (3 hop).

					["0.21:0.49:0.42:0.53:0.54:0.52:0.52:0.38"] = 315, -- Fizzcrank Airstrip, Stars' Rest, Wyrmrest Temple, Dalaran

This flight does not exist in the database.
```

**Comment by leatrix** [comment]
Flight time contributions are appreciated but only via email to flight please.  There have been thousands of submissions since Wrath went live and I really need them to be all in one place where they can be filtered and processed.

**Comment by jbreckel** [comment]
got it. sorry for the spam here then :)

and thanks for your work!
