### ISSUE TITLE
Add a mute for Reins of the Traveler's Tundra Mammoth's vendors

### ISSUE THREAD

**Issue by the-chuppa** [leatrix/leatrix-plus-wrath#152]
Please add a mute option for the vendor(s) on the Reins of the Traveler's Tundra Mammoth mount, specifically the machagnome.

**Comment by leatrix** [comment]
Good idea.  Added bikes, travelers and vaults to 3.0.23.alpha.2.

**Comment by the-chuppa** [comment]
I've updated to 3.0.23 where this was supposed to be added but I can still hear Gnimo. It's not just greeting sound, every time someone interacts with him, sells something, buys or buybacks, he makes a loud, mechanical sound.

**Comment by leatrix** [comment]
Thanks for the feedback.  It seems that in Wrath Classic, Gnimo sounds are shared with mechstrider wound sounds (this is different to retail where Gnimo doesn't have any sounds).

In 3.0.24.alpha.1, enabling either mute travelers or mute mechstriders will mute the mechstrider wound sounds which in turn will mute Gnimo.  Let me know if this update works ok for you.

**Comment by the-chuppa** [comment]
Works like a charm. Thank you for the quick implementation.
