### ISSUE TITLE
Request: Inclusion list for Sell Junk

### ISSUE THREAD

**Issue by freche** [leatrix/leatrix-plus-wrath#154]
There are white items are common and always sold to vendors so it would be nice to have an inclusion list for junk sell so we can include other items like Scrolls/Food/Water and other stuff not worth placing on the AH.

**Comment by leatrix** [comment]
In 3.0.26.alpha.2 and higher, non-junk items entered into the exclusions editbox will be sold automatically.  Junk items will be kept as before.
