### ISSUE TITLE
New feature: Alt-click to buyout an item on AH

### ISSUE THREAD

**Issue by Macumbatbc** [leatrix/leatrix-plus-wrath#155]
Hello,

I don't know if LeatrixPlus has this feature yet. 
I used back in the day the addon GnomishAuctionShrinker which has a feature to buyout an item on AH with Alt-Click. 
You gain a lot of time when you need to buy many different items ASAP.

I don't know if the API let you do this type of feature, but it's an insane QoL.

Thanks!

Note : Here is the addon if you want to check the code.
https://github.com/TekNoLogic/GnomishAuctionShrinker

**Comment by leatrix** [comment]
Suggestions appreciated.

**Comment by Macumbatbc** [comment]
> Suggestions appreciated.

Hello, will you add it then?
If you want me to test something, let me know !

For the moment i use this macro : 
`BrowseBuyoutButton:Click()
StaticPopup1Button1:Click()`
