### ISSUE TITLE
to add option to turn off checkboxes for head and cloak in the character panel

### ISSUE THREAD

**Issue by kkaczmarzyk** [leatrix/leatrix-plus-wrath#156]
add option to turn off checkboxes for head and cloak in the character panel as it is not that important and can overlap with other addons

**Comment by leatrix** [comment]
In LTP, everything is optional and modular.  You can disable the checkboxes by unchecking 'Show vanity controls' ('Interface').  It's disabled by default.  If you want to use the checkboxes but find they are in the way, hold down shift and right-click either of the checkboxes.
