### ISSUE TITLE
Enhancement Request: Audio one minute (or variable) warning for end of taxi flight time.

### ISSUE THREAD

**Issue by red13dotnet** [leatrix/leatrix-plus-wrath#157]
Enhancement Request: Audio, one minute (or variable) warning for end of taxi flight timer.

I have actually been trying to figure out how to do this on my own but I am finding that for long flights, an audio warning that I am close to arrival for taxi flights would be helpful.  Will submit a pull request if I ever find time to figure it out.

**Comment by leatrix** [comment]
In 3.0.33.alpha.1, the remaining flight time will be spoken using text to speech.  It will announce the remaining time once a minute then again at 30 seconds, 20 seconds and 10 seconds.  You can disable the announcement in the show flight times configuration panel.

**Comment by jtmunn** [comment]
I do not think this should be on by default, but maybe I am in the minority here.  I personally find this feature to be very annoying.

**Comment by leatrix** [comment]
If you never want to hear the speech, all you have to do is uncheck the setting.  It will never be checked again unless you wipe the entire addon settings so this is not an issue.

**Comment by jtmunn** [comment]
@leatrix - I totally get that and this is what I've done - was just relaying my feedback on it being on by default which I find that any addon w/ sounds should have the sound option muted by default, but again, just my honest opinion.  Thanks for your work on a great addon!

**Comment by leatrix** [comment]
You should have heard the first early alpha for this setting.  There was no text to speech - it used voice sounds from Unreal Tournament to announce the time remaining.  Oh boy, they were loud but it sure was fun... for a while.

**Comment by Calzeru** [comment]
I agree with jtmunn. Having leatrix loudly blast out "FLIGHT COMMENCED!!!!" completely unexpected was annoying af. Then I went into the options, unchecked it, and still BLAM *TWO MINUTES REMAINING!!!!". Guess it don't take effect until reloadui.

**Comment by JosefBud** [comment]
I totally appreciate some people wanted this feature, and I've turned it off, but I just wanted to also voice that I think this should be off by default. I don't think most people would want this. It also doesn't seem to use the game's volume settings, I have my master volume turned down super low (10%) and this text-to-speech is way louder.

**Comment by red13dotnet** [comment]
I just saw that this got added.  Found out during my first flight with the newest version.  That is amazing!  Thank you so much for adding this.  I tend to do other things while on long flights with my wireless headphones on and this is really helpful to know when I need to head back to the computer.

**Comment by leatrix** [comment]
The option tooltip clearly states:

> Changes to this setting will take effect on the next flight you take.

So toggling the setting on or off won't affect a flight you are currently on.
It's done this way because it's better for performance.

In 3.0.34.alpha.3, the speech volume will be set to the game master volume level.  If you don't want to hear the taxi flying sounds (flapping wings, etc), you can toggle the sound effects off with CTRL/S.  The speech will still be audible as long as the master volume level is up.

**Comment by JosefBud** [comment]
Thank you for quickly fixing the volume issue, as well as the rest of the work you do for this addon!

**Comment by leatrix** [comment]
> 3.0.34 - 17th October 2022
> - For 'Show flight times' text to speech, the speech volume will now be set to the game master volume slider and the option is now disabled by default.
>
