### ISSUE TITLE
Feature request: Movable objective and quest tracker

### ISSUE THREAD

**Issue by sMuve** [leatrix/leatrix-plus-wrath#159]
Hey there,
I have suggested the addition of a movable repair frame a couple of weeks ago. Thank you for the fast and good implemention.
Do you think it would also be possible to make the quest tracker and objective tracker (not the widget).

I tried to use the cluster scale again, but it is moving the right sidebars so much down, that I can not use the bottm right space for i.e. details.

Thank you for your work and I appreciate it soooo much!

**Comment by leatrix** [comment]
Suggestions appreciated.
