### ISSUE TITLE
Issue with ElvUI WrathArmory plugin.

### ISSUE THREAD

**Issue by FuriousZahn** [leatrix/leatrix-plus-wrath#160]
Hi,
In my character pane, I need to have the Enhance Dressup feature off for the character to use the entire pane as the ElvUI plugin provides. With Dressup on, the character sits on the top of the pane and doesn't use the bottom space where the stats used to be. 
Any chance for LTP not to mess with the plugin but also keep the Dressup feature on?

Thanks a lot for your work. Use this addon since day 1 classic.

**Comment by leatrix** [comment]
If Enhance dressup is enabled, a button is added to the character frame (near the top-left) that lets you toggle the character stats.  Is this what you want?

**Comment by leatrix** [comment]
Try 3.0.30.alpha.2.  If 'Enhance Dressup' is enabled and WrathArmory is installed, the character model will be full size.  If you have 'Show vanity controls' enabled, the helm and cloak checkboxes will be below the character model.
