### ISSUE TITLE
Flight master minimap tracking resets every time

### ISSUE THREAD

**Issue by thehallowedfire** [leatrix/leatrix-plus-wrath#162]
Hello. I'm not sure if it's LTP issue or bug in the game but flight master tracking on minimap resets every time when I close/open the game or use `/reload`.
Haven't tested it without addons though, but thought if you had similar issue and found the reason of that.
If it's the game bug you probably could easily fix this by automatic (by LTP) turning this tracking on every time when you load the game.

**Comment by leatrix** [comment]
The game bug affects multiple tracking settings as well as the None setting but it's nothing to do with addons.  You should report it to Blizzard with Game menu > Submit feedback or bug report > Submit a bug.  It's not something I can address with LTP.
