### ISSUE TITLE
Class Colors dont show anymore

### ISSUE THREAD

**Issue by Snauzer** [leatrix/leatrix-plus-wrath#163]
So i follow the "readfirst" things and it doesnt help. with only LeatrixPlus enabled the class colors dont show in chat. I asked in city chat and for other ppl it seems to work fine. I tried reinstalling the addon with the newest version but it doenst fix the problem. are there any other ways to find out what causing it ?

**Comment by leatrix** [comment]
Disable all other addons and test.  If that works fine, enable other addons gradually until you find the addon causing the problem.  Then either disable that addon or let let me know what that addon is and I can advise you further.

**Comment by jonathanw0** [comment]
I did as you stated above as I'm having the same issue. still not showing class colors

**Comment by Snauzer** [comment]
following all youre "readfirst" section contains "Disable all other addons and test" so it doesnt works

**Comment by Snauzer** [comment]
there was probably an update. now you have to right click on settings and manually activate the class colors in the standard chat window

you can close this ticket

**Comment by leatrix** [comment]
The game chat settings only allow you to toggle the channels and choose the color used for each channel.  There is no setting to toggle class colors.

**Comment by djv912** [comment]
Class colors in chat aren't working for me either. I tried reinstalling and disabling other addons etc. Still not working

**Comment by leatrix** [comment]
Works fine for me.  Enter this in chat and tell me what the output is:
`/ltp cv chatClassColorOverride`

**Comment by djv912** [comment]
Output is 0

**Comment by kirkjames371** [comment]
0 as well, having the same issue. Newest update broke this feature

**Comment by spfaffly** [comment]
I disabled all the addons - ran `/ltp wipe` and tried to check the "Use class colors in chat" and nothing as well.

`/ltp cv chatClassColorOverride` also returns 0 for me.

**Comment by leatrix** [comment]
Sorry about that and thank you for the reports and information.  This should be fixed in 3.0.32.
