### ISSUE TITLE
Request: Auto Turn in Quests

### ISSUE THREAD

**Issue by FireEmerald** [leatrix/leatrix-plus-wrath#169]
**Description:**
Add an option which **auto turns in** completed quests when talking to a npc.
If a completed quest **does require** to select a reward, go until that screen.
Do that for all quests which are complete-able for the npc speaking.

There is already an option under **Auto > Character** to auto accept quests (the counter part).

**Why is this feature important:**
It costs seconds and seconds to select always the completed quest and then say turn-in if no reward is to select.

**Comment by leatrix** [comment]
Feedback appreciated.

**Comment by FireEmerald** [comment]
@leatrix  Why was it closed? Is it to hard to implement? Or what's the reason?
