### ISSUE TITLE
Minimap Icon Double Up

### ISSUE THREAD

**Issue by BedDweller** [leatrix/leatrix-plus-wrath#173]
Quesing LTP and Questie is causing a double up on the map icons for quests.
I would prefer to just have Questie's icons to show as it has options for many other PoI.

Would be awesome if you can add a toggle for LTP map icons in the Enchance Minimap option.

Thank you.

![image](https://user-images.githubusercontent.com/6633140/198252663-258bfcde-5f9d-4093-9abc-ceb95f2b263e.png)

**Comment by leatrix** [comment]
Those aren't LTP map icons.  The default UI shows quest markers without addons and that is what you are seeing.  When you use Questie, it also adds quest markers to the minimap so you end up seeing double.  If you only want to see Questie quest markers, this is something you need to take up with Questie.  It's nothing to do with LTP.
