### ISSUE TITLE
Feature Request: Right click to quickly swap talents

### ISSUE THREAD

**Issue by TylerR909** [leatrix/leatrix-plus-wrath#177]
Hi there, I tried to fork and add this real quick to propose a new feature via PR, but had issues opening `/ltp` even on a clean branch. Probably my problem, not yours.

Anyway, when I open my talents in Wrath, with Dual Spec, I'd like to be able to simply right click the Primary/Secondary tab to swap between talents.

The heart of the feature is `SetActiveTalentGroup(group)` where group = 1 or 2. Looks like the Blizzard XML has `<CheckButton name="PlayerSpecTab1" id="1">` and one for PlayerSpecTab2. Been a minute since I've worked on any addons, but it looks like you may be able to...

```lua
function QuickSwapTalents()
  -- check for dual spec
  if (not PlayerSpecTab1 or not PlayerSpecTab2) then return end

  -- Register buttons
  PlayerSpecTab1:RegisterForClicks("LeftButtonUp", "RightButtonUp") -- left preserves original leftclick behavior  
  PlayerSpecTab1:HookScript("OnClick", function(self,button,down)
    if button ~= "RightButton" then return end
    if (GetActiveTalentGroup() ~= 1) then SetActiveTalentGroup(1) end
  end)

  PlayerSpecTab2:RegisterForClicks("LeftButtonUp", "RightButtonUp")
  PlayerSpecTab2:HookScript("OnClick",function(self,button,down)
    if button ~= "RightButton" then return end
    if (GetActiveTalentGroup() ~= 2) then SetActiveTalentGroup(2) end
  end)
end
```

Tested the middle chunk ingame with a couple `/dump` commands and it worked out pretty great. Not sure what other edge cases you'd like to consider. 

If I had to decide where to put it, I'd suggest Interface > Extras under "Quick swap talents" with the tooltip "Right click the Primary or Secondary Talents button to quickly swap to that talent group"

Thanks for your consideration!

**Comment by leatrix** [comment]
Suggestions appreciated.
