### ISSUE TITLE
shrank action bar

### ISSUE THREAD

**Issue by MRpEGGasus** [leatrix/leatrix-plus-wrath#178]
after enabled the addon, my action bars at the right are massively shrankened.. 
![image](https://user-images.githubusercontent.com/23392529/199491586-95e70eff-96e7-4ac7-bade-64fcec5f204a.png)

**Comment by leatrix** [comment]
You enabled 'Enhance minimap' ('Interface') and adjusted the cluster scale slider without reading the cluster scale slider tooltip.

![image](https://user-images.githubusercontent.com/58888415/199566038-76008d88-6cd9-4d8c-a69a-3e739d47e862.png)

**Comment by MRpEGGasus** [comment]
> You enabled 'Enhance minimap' ('Interface') and adjusted the cluster scale slider without reading the cluster scale slider tooltip.
> 
> ![image](https://user-images.githubusercontent.com/58888415/199566038-76008d88-6cd9-4d8c-a69a-3e739d47e862.png)
> 
> A solid workaround for this is to use an action bar addon such as Bartender. It's a very good action bar addon and much better than Blizzard's Edit Mode. Bartender action bars won't shrink and you can do more with them. Profile support is better too and unlike Blizzard's Edit Mode, Bartender doesn't cause problems for other addons.

thx a lot! the issue is settled!
