### ISSUE TITLE
Feature Request: Auto-Invite Battle.net Friends

### ISSUE THREAD

**Issue by serasvis** [leatrix/leatrix-plus-wrath#179]
A lot of people in my guild use the Leatrix auto-invite guildies/friends feature. A couple of people in my guild have a BN name that is identical to their in-game character's name, and whispers prioritize BN chat over in-game. I've heard of one example of someone deciding to unfriend someone else on BN because the auto-invite feature didn't work, so thought I'd make this request as it probably happens to more people out there. I was able to write a custom weakaura that can do this. It listens for the 'CHAT_MSG_BN_WHISPER' event and runs this code:
```
function(event,...)
    local vars = {...}
    if vars[1] == 'inv' then
        for i=1,BNGetNumFriends() do
            local _,n,_,_,c = BNGetFriendInfo(i)
            if vars[2]==n then
                InviteUnit(c)
                break
            end
        end
    end
end
```
Thanks :)

**Comment by leatrix** [comment]
In 3.0.104.alpha.1, the friend checking code used for the options in the social menu has been updated to match Dragonlands.  If you still have issues after you and anyone you are trying to group with has installed this update, let me know.
