### ISSUE TITLE
Feature Request: Auto promote (sub-feature to the auto invite)

### ISSUE THREAD

**Issue by Suttekluden** [leatrix/leatrix-plus-wrath#180]
I would really love the option to input a list of names that should be auto promoted upon joining a raidgroup I am the leader of.
(I am currently using Method Raid Tools for autoinvite and autopromote only and it feels terrible to use that large an addon for such a small feature).

**I imagine something like:**
Assists: name1,name2,name3,name4,name5,....

Main Tanks: tank1,tank2,tank3,....

[checkbox_auto_set_lootoption_to_masterloot]
Master Looter: name1,name2_if_name1_is_not_present,...

_- Cheers for the great addons and hope this could be a future implementation._

**Comment by leatrix** [comment]
Suggestions appreciated.
