### ISSUE TITLE
Feature Request: Seperate Buffs and Debuffs. Allow grow from left options (WOTLK)

### ISSUE THREAD

**Issue by n47h4ni3l** [leatrix/leatrix-plus-wrath#182]
Hi. Fantastic addon. I would like to able to customise the buff frames. I want to put my buffs in the top left of my screen so a grow left option would be helpful. I want to move my debuffs to the top of my player potrait frame. TIA if this can be done

**Comment by leatrix** [comment]
Suggestions appreciated.
