### ISSUE TITLE
ltp 3.0.55 broke Crafting interface 

### ISSUE THREAD

**Issue by blacksoul178** [leatrix/leatrix-plus-wrath#183]
this morning after getting through with 3.0.55  i am getting this mess,    reverting to 3.0.54 works atm

![ltp crafting bug](https://user-images.githubusercontent.com/118370614/202210811-cb601472-0c68-43d0-85e4-d0f3ac12f7b6.png)

**Comment by gelsbern** [comment]
This same thing also happens on the NPC training windows.

**Comment by zdinch** [comment]
Since the last update 3.0.55 the questlog also has an error.

![ss+(2022-11-16+at+05 03 37)](https://user-images.githubusercontent.com/84704512/202250331-f4f80b86-e317-448a-be71-5687d930f0a1.png)

**Comment by leatrix** [comment]
Sorry about that.  Should be fixed in 3.0.56.  Thanks for the reports.
