### ISSUE TITLE
Feature Request: Automate confirmation for Emblem exchange

### ISSUE THREAD

**Issue by d3xavier** [leatrix/leatrix-plus-wrath#184]
When exchanging Emblems in Dalaran at NPC: "Usuri Brightcoin".  There is a confirmation window, which makes exchanging emblems incredibly annoying.  Adding automation for accepting the Emblem exchange would be a help, as you can only exchange 1 emblem at a time, and if you need to exchange 120 emblems, that is a lot of clicking.

![image](https://user-images.githubusercontent.com/4826700/202766312-d535990f-103f-4b65-8d7e-233266329d5b.png)
![image](https://user-images.githubusercontent.com/4826700/202766368-15123c0b-829f-4c59-b081-e1892277234f.png)

**Comment by d3xavier** [comment]
Also, just to mention, there doesn't appear to be a way to buy/exchange more than one Emblem at a time through a Shift+Click.  But there is a Macro that does work:

/script BuyMerchantItem(1, X) replacing X with the number of Emblems of Valor you want to exchange for Emblems of Heroism.

**Comment by leatrix** [comment]
Suggestions appreciated.
