### ISSUE TITLE
Error at Event logout

### ISSUE THREAD

**Issue by BananaYuppie** [leatrix/leatrix-plus-wrath#186]
7x Interface\AddOns\Leatrix_Plus\Leatrix_Plus-3.0.57.lua:3586: attempt to concatenate local 'realm' (a nil value)
[string "@Interface\AddOns\Leatrix_Plus\Leatrix_Plus-3.0.57.lua"]:3586: in function <Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:3583>

Locals:
self = <unnamed> {
 0 = <userdata>
}
event = "PLAYER_LOGOUT"
name = "Tekax"
realm = nil
(*temporary) = <table> {
 HideMiniZoomBtns = "Off"
 ViewPortBottom = 0
 BuffFrameX = -205
 ManageFocus = "Off"
 BuffFrameY = -13
 VehicleScale = 1
 TimerY = -96
 MusicContinent = "Random"
 ClassColPlayer = "On"
 RecentChatSize = 170
 ManageWidget = "Off"
 ShowMinimapIcon = "On"
 EasyItemDestroy = "Off"
 ChatTemp5 = <table> {
 }
 InvKey = "inv"
 SetWeatherDensity = "Off"
 ShowVanityControls = "Off"
 FlightBarY = -66
 minimapPos = 108.208535
 FlightBarBackground = "On"
 MinimapR = "TOPRIGHT"
 MinimapSize = 140
 FlightBarContribute = "On"
 FrmEnabled = "Off"
 MuteBrooms = "Off"
 ChatHistoryTime = 1668990980
 ChatTemp4 = <table> {
 }
 TipCursorY = 0
 LeaStartPage = 5
 FriendlyGuild = "On"
 MainPanelR = "CENTER"
 NoGryphons = "Off"
 DismountNoTaxi = "On"
 InviteFromWhisper = "Off"
 MinimapScale = 1
 TimerScale = 1
 ViewPortTop = 0
 AutoReleasePvP = "Off"
 HideMacroText = "Off"
 MinimapX = -17
 TipCursorX = 0
 AutoResNoCombat = "On"
 WowheadLinkComments = "Off"
 VanityAltLayout = "Off"
 TipHideInCombat = "Off"
 UseArrowKeysInChat = "On"
 ManageDurability = "Off"
 AcceptPartyFriends = "On"
 MoreFontSizes = "Off"
 WidgetX = 0
 CombineAddonButtons = "On"
 FlightBarWidth = 230
 RestoreChatMessages = "On"
 FirstRunMessageSeen = true
 NoCooldownDuration = "On"
 FlightBarSpeech = "Off"
 WidgetA = "TOP"
 SquareMinimap = "On"
 WidgetScale = 1
 DurabilityScale = 1
 NoChatFade = "Off"
 MuteGameSounds = "Off"
 MuteYawns = "Off"
 NoRestedEmotes = "Off"
 NoPartyInvites = "Off"
 CombatPlates = "Off"
 FocusX = 0
 MinimapA = "TOPRIGHT"
 TipHideShiftOverride = "On"
 HideZoneText = "Off"
 TimerX = -5
 EnhanceQuestTaller = "On"
 AhBuyoutOnly = "Off"
 EnhanceDressup = "Off"
 CustomAddonButtons = <table> {
 }
 ChatTemp6 = <table> {
 }
 BuffFrameScale = 1
 HideErrorMessages = "Off"
 DurabilityX = 0
 ShowWhoPinged = "On"
 ChatHistory5Count = 49
 MinimapModder = "On"
 AutoQuestAvailable = "On"
 BlockDuelSpam = "Off"
 DressupItemButtons = "On"
 AutoQuestShift = "Off"
 HideMiniClock = "Off"
 MuteAdal = "Off"
 DurabilityY = -192
 LeaPlusQuestFontSize = 12
 TipShowTarget = "On"
 CharAddonList = "Off"
 FocusR = "CENTER"
 MainPanelX = 420.074249
 MuteScreech = "Off"
 NoDuelRequests = "Off"
 ManageVehicle = "Off"
 AhExtras = "Off"
 FlightBarA = "TOP"
 ChatHistory4Count = 64
 QuestFontChange = "Off"
 BlockSpellLinks = "Off"
 MuteReady = "Off"
 ChatHistory1 = <table> {
 }
 MuteGyrocopters = "Off"
 ChatTemp1 = <table> {
 }
 MuteRipper = "Off"
 ShowCooldownID = "On"
 UseEasyChatResizing = "Off"
 NoAlerts = "Off"
 FlightBarDestination = "On"
 ChatHistory4 = <table> {
 }
 AutoRepairGuildFunds = "On"
 HideMiniAddonButtons = "On"
 BuffFrameA = "TOPRIGHT"
 DressupAnimControl = "On"
 NoClassBar = "Off"
 VehicleA = "TOPRIGHT"
 MuteChimes = "Off"
 FlightBarFillBar = "Off"
 DismountNoMoving = "On"
 EnhanceQuestDifficulty = "On"
 TooltipAnchorMenu = 1
 ShowRaidToggle = "Off"
 ShowVendorPrice = "On"
 MuteTravelers = "Off"
 EnhanceProfessions = "On"
 CooldownsOnPlayer = "Off"
 AutoSellExcludeList = ""
 Frames = <table> {
 }
 ShowPlayerChain = "Off"
 EnhanceQuestLog = "Off"
 WidgetY = -15
 EnhanceQuestHeaders = "On"
 FasterLooting = "On"
 TipNoHealthBar = "Off"
 FilterChatMessages = "Off"
 MaxCameraZoom = "Off"
 HideMiniMapButton = "On"
 FlightBarScale = 2
 NoScreenEffects = "Off"
 MuteStriders = "Off"
 MinimapNoScale = "Off"
 TipOffsetX = -13
 MaxChatHstory = "On"
 DismountNoResource = "On"
 BlockDrunkenSpam = "Off"
 ManageBuffs = "Off"
 ViewPortAlpha = 0
 ShowWowheadLinks = "Off"
 ShowFreeBagSlots = "Off"
 UnclampChat = "Off"
 PlayerChainMenu = 2
 TimerR = "TOP"
 MuteMechSteps = "Off"
 NoConfirmLoot = "Off"
 ClassColFrames = "Off"
 MuteVaults = "Off"
 NoStickyChat = "Off"
 ViewPortResizeBottom = 0
 LeaPlusMailFontSize = 15
 ViewPortResizeTop = 0
 WidgetR = "TOP"
 StandAndDismount = "Off"
 NoFriendRequests = "Off"
 AutoRepairShowSummary = "On"
 PlusPanelScale = 1
 FocusY = 0
 ShowBagSearchBox = "Off"
 DurabilityStatus = "Off"
 NoChatButtons = "Off"
 EnhanceQuestLevels = "On"
 FlightBarX

**Comment by leatrix** [comment]
This is a rare error for some people using 'Restore chat messages' ('Chat').  It should be fixed in 3.0.59 (released just now).  Please confirm if it is because I'm not able to replicate this particular error.
