### ISSUE TITLE
Quest text clipping

### ISSUE THREAD

**Issue by KredesX** [leatrix/leatrix-plus-wrath#188]
My quest text is clipping the window when i enable "enhance quest log", as seen below

https://i.imgur.com/N1JEXNW.png

**Comment by leatrix** [comment]
Are you using Lort UI?
If so, there is a solution here until the author updates the addon.
https://github.com/leatrix/leatrix-plus-wrath/issues/185#issuecomment-1321869578

**Comment by KredesX** [comment]
Indeed i am, i did wonder if Lorti UI had anything to do with it.

I'll try that, thanks!
