### ISSUE TITLE
 Feature request: Add option to only show first character of a chat channel

### ISSUE THREAD

**Issue by sadamczyk** [leatrix/leatrix-plus-wrath#189]
I would like an option for the chat to only show the first character/number of a chat channel.
`[2. Trade]` would become just `[2]`, `[Guild]` would become `[G]` etc.
This in combination with the channel color (green for guild etc.) should be enough to clearly identify 99% of channels, and this would make the chat a lot cleaner.

**Comment by leatrix** [comment]
Suggestions appreciated.
