### ISSUE TITLE
Bug: Gossip window does not close when selecting training option

### ISSUE THREAD

**Issue by clong-** [leatrix/leatrix-plus-wrath#191]
When the "Interface > Enhance trainers" option is enabled, the trainer gossip window does not close when selecting the training option. Instead it stays open but is non-interactable except to close it. It even stays open when running out of interact range with the NPC. This happens with both class and profession trainers.

The default Blizz behavior is that the gossip window closes when the training window opens.

Confirmed behavior with all addons disabled except Leatrix Plus. Also tested without all other options disabled in Leatrix Plus -- appears to be specifically related to the "Enhance trainers" option being enabled.

Game version 3.4.1 (47612) (Release x64)
Addon version 3.0.85-wrath

**Comment by clong-** [comment]
I've just found that this also occurs with the AH robot in Dalaran. Selecting the gossip option to open the AH exhibits the same behavior described above.

**Comment by leatrix** [comment]
Thanks for the report.  The trainers frame issue should be fixed in 3.0.86.  For the auction house robot, can you try that with all addons (including Leatrix addons) disabled and let me know what happens?  Leatrix Plus doesn't modify the layout of the auction house frame at all.

**Comment by clong-** [comment]
Ah, good call. Looks like the AH one is related to TSM, not Leatrix Plus. Thanks for the quick response on the trainer issue!
