### ISSUE TITLE
LUA erorr on Ulduar NPCs

### ISSUE THREAD

**Issue by GregoryGH** [leatrix/leatrix-plus-wrath#192]
1x Leatrix_Plus/Leatrix_Plus.lua:2130: attempt to index global 'GossipFrameGreetingPanel' (a nil value)
[string "@Leatrix_Plus/Leatrix_Plus.lua"]:2130: in function <Leatrix_Plus/Leatrix_Plus.lua:2033>

**Comment by leatrix** [comment]
Many thanks for your bug report.  It's fixed in 3.0.90.
