### ISSUE TITLE
Lua error when opening gossip windows (talking to npc's)

### ISSUE THREAD

**Issue by ssateneth** [leatrix/leatrix-plus-wrath#193]
All elements of gossip frames are now part of the parent GossipFrame and individual parts of the gossip frame do not have their own global name. For example, GossipFrameGreetingPanel is now located at GossipFrame["GreetingPanel"]

Message: Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua:2130: attempt to index global 'GossipFrameGreetingPanel' (a nil value)
Time: Sat Jan 21 19:36:08 2023
Count: 1
Stack: Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua:2130: attempt to index global 'GossipFrameGreetingPanel' (a nil value)
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua"]:2130: in function <Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua:2033>

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by leatrix** [comment]
https://github.com/leatrix/leatrix-plus-wrath/issues/192
