### ISSUE TITLE
Rightclick on minimap ends with an error

### ISSUE THREAD

**Issue by madbyte** [leatrix/leatrix-plus-wrath#194]
Hi,
I'm using version 3.0.92 of Leatrix Plus.
If the option "Combine addon buttons" (Enhance minimap) is active, it's not possible to right click on the minimap without getting an error.
`Message: Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua line 4462:
   attempt to index field 'db' (a nil value)
Debug:
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua"]:4462:
      Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua:4419`
[minimap_error.txt](https://github.com/leatrix/leatrix-plus-wrath/files/10482046/minimap_error.txt)
It is caused by the following line: (Leatrix_Plus.lua Line 4462)
`if not button.db.hide then`

Since I have no idea how WoW addons are working, I just change the line  to "if true then" and can at least confirm, that the rest of the code for this option doesn't raise any further errors.

**Comment by leatrix** [comment]
Please try 3.0.93.alpha.1.  In CurseForge App, you can switch to alpha releases by right-clicking the addon in your addon listing and changing the release type.

**Comment by madbyte** [comment]
Thanks for the quick response.
The alpha version has fixed the error.
