### ISSUE TITLE
Unable to open any Leatrix addon

### ISSUE THREAD

**Issue by Stefen74** [leatrix/leatrix-plus-wrath#195]
Upon trying any of the following ...

/run leamaps
/run leaplus
/run leasound

I get an identical lua error for each one ...

Message: [string "leamaps"]:1: '=' expected near '<eof>'
Time: Wed Jan 25 15:45:52 2023
Count: 1
Stack: [string "leamaps"]:1: '=' expected near '<eof>'
[string "=[C]"]: in function `RunScript'
[string "@Interface/FrameXML/ChatFrame.lua"]:2201: in function `?'
[string "@Interface/FrameXML/ChatFrame.lua"]:4938: in function `ChatEdit_ParseText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4601: in function `ChatEdit_SendText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4637: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:121_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:121_OnEnterPressed"]:1>

Locals: (*temporary) = "leamaps"

I have disabled all other addons and had only the 3 Leatrix addons above running, and I still get the error.

Being the only one who seems to be reporting this, I have a fear this is an issue on my end, and not the addon?

Regards

Stef

**Comment by leatrix** [comment]
For Wrath Classic, it's **/run leaplus()** until Blizzard fix their slash command issue.
For Dragonflight and Classic Era, it's **/ltp**.
You can go into the game keybindings menu to assign a key to toggle any Leatrix addon.  For LTP and LTM, you can click the addon minimap butons.
