### ISSUE TITLE
Text-to-Speech Using Different Ouput

### ISSUE THREAD

**Issue by gn1sha** [leatrix/leatrix-plus-wrath#197]
When you have the Text-to-Speech enabled for the Flight Timer, the audio output used isn't what game has set. 

The game Audio Output is set to my speakers. Voice chat output is also set to my speakers. The audio appears to be coming from 'System Default' which is my USB headset.

This occurs with all other addons disabled, and am on the latest version.

**Comment by leatrix** [comment]
Blizzard's text to speech system uses the system default device for output.  It ignores the game sound output setting in the system sound panel.  If you want TTS output to your speakers, you would need to set your operating system default audio playback device to your speakers.  Then launch Wow and the system default device should now be set to your speakers too.

**Comment by gn1sha** [comment]
Awesome, thanks!
