### ISSUE TITLE
[Feature Request] Mute Rhonin

### ISSUE THREAD

**Issue by jazminite** [leatrix/leatrix-plus-wrath#198]
Feature Request - Add Rhonin to "Mute game sounds" menu. He has a loud, long, annoying dialog every time someone turns in the quest in Dalaran:
![image](https://user-images.githubusercontent.com/65823478/216548681-1eac8417-56ba-4689-ac30-d6d4b32c33f7.png)

**Comment by leatrix** [comment]
Good idea.  Added to 3.0.102.

**Comment by jazminite** [comment]
> Good idea. Added to 3.0.102.

Thanks so much!!!
