### ISSUE TITLE
Feature Request - mute Mimiron's Head mount

### ISSUE THREAD

**Issue by be-rational** [leatrix/leatrix-plus-wrath#202]
This mount is so loud and obnoxious please add it to the Mute game sounds list <3

**Comment by leatrix** [comment]
> 3.0.109.alpha.1 - 20th February 2023
> - For 'Mute game sounds' ('System'), added new sounds to the 'Gyrocopters' setting (including Mimiron's Head).

Untested so perhaps you can let me know.

**Comment by be-rational** [comment]
It works, thanks a lot <3
